"""
Validation script for OFI_MC Factor
Compares OFI_MC (Market Cap Normalized) vs OFI_Vol (Volume Normalized)
Using synthetic data generated by generate_realistic_hfd.py
"""

import numpy as np
import sys
import os
import time

# Ensure we can import the factor
sys.path.append(os.getcwd())

try:
    from research.alpha_factors.ofi_mc_factor import OFIMCFactor
except ImportError:
    # Fallback if running from wrong dir
    try:
        sys.path.append('research/alpha_factors')
        from ofi_mc_factor import OFIMCFactor
    except:
        print("Error importing OFIMCFactor. Run from project root.")
        sys.exit(1)

# Constants from generate_realistic_hfd.py
DEPTH_EVENT = 1
TRADE_EVENT = 2
BUY = 1
SELL = -1 
# Note: In generate_realistic_hfd, side 1=Bid, -1=Ask usually for trading.
# But let's verify logic:
# process_event adds (DEPTH_EVENT, px, qty, BUY) for Limit Bid.
# So ival=1 is Bid, ival=-1 is Ask?
# Let's assume standard: side 1 -> Bid, side -1 (or 0 or 2?) -> Ask.
# Usually 1=Buy/Bid, 2(or -1)=Sell/Ask.
# We will inspect unique values of 'ival' in the script if needed.
# For now assume 1=Bid, -1=Ask (as typical in many internal systems) or check data.
# Update: generate_realistic_hfd.py uses constants. Let's assume typical:
# Bid updates affect Bid Price/Qty. Ask updates affect Ask Price/Qty.

def run_validation(data_path, limit_events=5000000):
    print(f"Loading data from {data_path}...")
    if not os.path.exists(data_path):
        print("Data file not found.")
        return
        
    loaded = np.load(data_path)
    data = loaded['data']['data'] if 'data' in loaded['data'].dtype.names else loaded['data']
    # Handle structured array nesting if any
    
    print(f"Loaded {len(data)} events. Using first {limit_events}...")
    data = data[:limit_events]
    
    # Initialize Factor
    # Market Cap for TXF is roughly Price * 200 * OpenInterest
    # Say Price=20000, Multiplier=200, OI=100000 -> MC = 400 Billion
    # For relative comparison, constant doesn't matter too much, but let's be realistic.
    factor = OFIMCFactor(market_cap=400e9) 
    
    # Validation Buckets (1-minute bars)
    # Timestamps are in nanoseconds or microseconds? 
    # generate_realistic_hfd uses strictly increasing 'local_ts' (in ns usually).
    # Let's check first timestamp.
    t0 = data[0]['local_ts']
    bin_size = 60 * 1e9 # 1 minute in ns
    
    # Outputs
    bin_returns = []
    bin_ofi_mc = []
    bin_ofi_vol = []
    
    current_bin_idx = 0
    current_bin_start = t0
    
    # LOB State (Top of Book)
    best_bid = 0.0
    best_ask = float('inf')
    bid_qty = 0.0
    ask_qty = 0.0
    
    # Keep track of multiple levels? No, OFI usually uses Top.
    # But synthetic data events update specific levels.
    # We need a minimal LOB to know which level is best.
    # Or simplified: Just Map: Price -> Qty. Max(Price) where Qty>0 is Best Bid.
    bids = {}
    asks = {}
    
    start_time = time.time()
    
    # Accumulators for current bin
    last_mid = None
    accum_ofi_mc = 0.0 # We will just sample the factor value at end of bin? 
    # Or accumulate delta?
    # Factor computes cumulative. So Bin OFI = Factor_End - Factor_Start.
    prev_factor_mc = 0.0
    prev_factor_vol = 0.0
    
    bin_open_mid = None
    
    print("Processing events...")
    
    # Pre-scan unique sides to confirm
    # sides = np.unique(data['ival'])
    # print(f"Sides found: {sides}")
    
    for i, ev in enumerate(data):
        etype = ev['ev']
        px = ev['px']
        qty = ev['qty']
        side = ev['ival'] # 1 or -1 or 2?
        ts = ev['local_ts']
        
        # Update LOB
        if etype == DEPTH_EVENT:
            # qty is the NEW quantity at this price level
            # In generate_realistic_hfd.py: self.state.bid_quantities[level] += qty (wait)
            # Actually generate_realistic_hfd emits: (DEPTH_EVENT, px, NEW_QTY, side)
            # It sends the absolute quantity.
            # Side: 1=Bid, -1=Ask (Assumed)
            
            if side == 1: # Bid
                if qty <= 0:
                    if px in bids: del bids[px]
                else:
                    bids[px] = qty
            elif side in [-1, 2]: # Ask (Check raw values later)
                # Assuming -1 for now
                if qty <= 0:
                    if px in asks: del asks[px]
                else:
                    asks[px] = qty
            
            # Recompute BBO
            best_bid = max(bids.keys()) if bids else 0.0
            bid_qty = bids[best_bid] if best_bid in bids else 0.0
            
            best_ask = min(asks.keys()) if asks else float('inf')
            ask_qty = asks[best_ask] if best_ask in asks else 0.0
            
        trade_vol = 0.0
        if etype == TRADE_EVENT:
            trade_vol = qty
            # Trades might consume liquidity, but generating script normally emits depth update after trade.
            # So we rely on depth updates for BBO.
            
        # Update Factor
        # Need realistic BBO.
        if best_bid > 0 and best_ask < float('inf'):
            mid = (best_bid + best_ask) / 2.0
            if last_mid is None: last_mid = mid
            if bin_open_mid is None: bin_open_mid = mid
            
            res = factor.compute(best_bid, bid_qty, best_ask, ask_qty, trade_vol, mid)
            last_mid = mid
        
        # Check Bins
        if ts >= current_bin_start + bin_size:
            # End of bin
            # 1. Calculate Signal for this bin: (Current Cumul - Prev Cumul)
            # Actually OFI Factor accumulates.
            # Signal_MC = (Cumul_MC_Now - Cumul_MC_Start)
            # Signal_Vol = (Cumul_OFI_Now - Cumul_OFI_Start) / (Cumul_Vol_Now - Cumul_Vol_Start)
            # The 'ofi_vol_norm' in factor is Cumulative / Cumulative.
            # For bin signal, we want Delta OFI / Delta Vol.
            
            curr_ofi_raw = factor.cumulative_ofi
            curr_vol_raw = factor.cumulative_vol
            
            # Need to store state at start of bin
            # We need a stateful validation class or just vars
            # But let's use the values from factor object
            
            # Wait, I need previous bin's cumulative values to get Delta
            # Let's store them
            if 'bin_start_ofi' not in locals():
                bin_start_ofi = 0.0
                bin_start_vol = 0.0
            
            delta_ofi = curr_ofi_raw - bin_start_ofi
            delta_vol = curr_vol_raw - bin_start_vol
            
            # Calculate Signals
            sig_mc = delta_ofi  # / Constant (Scale doesn't affect IC)
            if delta_vol > 0:
                sig_vol = delta_ofi / delta_vol
            else:
                sig_vol = 0.0
                
            # Calculate Return for NEXT bin (Label)
            # We can't know next bin return yet. 
            # We align: Signal(Bin K) vs Return(Bin K+1).
            # So we verify prediction power.
            
            # At end of Bin K, we record Signal K.
            # We also record Close Price K.
            # Return K+1 = (Close K+1 - Close K) / Close K.
            
            bin_ofi_mc.append(sig_mc)
            bin_ofi_vol.append(sig_vol)
            bin_returns.append(last_mid) # Store price series first
            
            # Reset for next bin
            bin_start_ofi = curr_ofi_raw
            bin_start_vol = curr_vol_raw
            current_bin_start += bin_size
            
            # Progress
            if len(bin_returns) % 100 == 0:
                print(f"Processed {len(bin_returns)} bins...")

    print(f"Loop finished in {time.time() - start_time:.2f}s")
    
    # Calculate Returns
    prices = np.array(bin_returns)
    # Forward Returns: r_{t+1} = (p_{t+1} - p_t) / p_t
    # Signal_t predicts r_{t+1}
    
    if len(prices) < 2:
        print("Not enough data.")
        return
        
    fwd_returns = np.diff(prices) / prices[:-1]
    
    # Align signals
    # bin_ofi_mc has length N. fwd_returns has length N-1.
    # Signal[0] predicts Return[0] (which is p1 - p0)
    # So we use Signals[:-1] and Returns
    
    sigs_mc = np.array(bin_ofi_mc[:-1])
    sigs_vol = np.array(bin_ofi_vol[:-1])
    
    # Remove NaNs
    valid = ~np.isnan(fwd_returns) & ~np.isnan(sigs_mc) & ~np.isnan(sigs_vol)
    
    # Correlation (IC)
    ic_mc = np.corrcoef(sigs_mc[valid], fwd_returns[valid])[0, 1]
    ic_vol = np.corrcoef(sigs_vol[valid], fwd_returns[valid])[0, 1]
    
    print("\n" + "="*50)
    print("OFI Factor Validation Results (1-Minute Horizon)")
    print("="*50)
    print(f"Events Processed: {limit_events}")
    print(f"Bins Generated:   {len(fwd_returns)}")
    print("-" * 30)
    print(f"IC (OFI_MC):      {ic_mc:.4f}")
    print(f"IC (OFI_Vol):     {ic_vol:.4f}")
    print("-" * 30)
    
    if ic_mc > ic_vol:
        print("✅ Hypothesis Confirmed: Market Cap Norm (Constant) > Volume Norm")
        print(f"Improvement: {(ic_mc/ic_vol - 1)*100:.1f}%")
    else:
        print("❌ Hypothesis Failed: Volume Norm is better")
        
if __name__ == "__main__":
    # Use the 1-year data generated
    data_file = "data/txf_1year_2025.npz"
    # Or fallback to test data
    if not os.path.exists(data_file):
        data_file = "data/test_realistic_v4.npz"
        
    run_validation(data_file)
