"""CLI commands: run, init, check, wizard."""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import sys
import textwrap
from typing import Any, Dict

from structlog import get_logger

from hft_platform.config.loader import (
    detect_live_credentials,
    load_settings,
    summarize_settings,
)

from ._utils import _safe_write

logger = get_logger("cli")


def cmd_run(args: argparse.Namespace) -> None:
    os.environ.setdefault("HFT_RUNTIME_ROLE", "engine")
    runtime_role = str(os.getenv("HFT_RUNTIME_ROLE", "engine")).strip().lower().replace("-", "_")
    if runtime_role != "engine":
        logger.warning(
            "hft run invoked with non-engine runtime role; feed client creation may be disabled",
            runtime_role=runtime_role,
        )

    mode = args.mode or args.mode_flag or _resolve_default_mode()
    cli_overrides: Dict[str, Any] = {
        "mode": mode,
        "symbols": args.symbols or None,
    }
    if args.strategy:
        cli_overrides["strategy"] = {
            "id": args.strategy,
            "module": args.strategy_module or "hft_platform.strategies.simple_mm",
            "class": args.strategy_class or "SimpleMarketMaker",
            "params": {},
        }
    settings, defaults = load_settings({k: v for k, v in cli_overrides.items() if v})

    downgraded = None
    if settings.get("mode") == "live" and not detect_live_credentials():
        downgraded = "sim"
        settings["mode"] = "sim"
        logger.warning("No Shioaji credentials found, downgrading to sim mode")

    summary = summarize_settings(settings, downgraded_mode=downgraded)
    print(f"[hft run] {summary}")
    if downgraded:
        print("Hint: set SHIOAJI_API_KEY / SHIOAJI_SECRET_KEY to enable live.")

    if settings.get("mode") == "replay":
        print("Replay mode not yet wired; please use backtest runner directly.")
        return

    # Live/Sim share the same runtime pipeline; sim runs with Shioaji stub.
    from prometheus_client import start_http_server

    from hft_platform.main import HFTSystem
    from hft_platform.observability.metrics import MetricsRegistry

    MetricsRegistry.get()  # fully populate REGISTRY before scrape thread starts
    start_http_server(settings.get("prometheus_port", 9090))
    print(f"Prometheus metrics started on :{settings.get('prometheus_port', 9090)}")

    system = HFTSystem(settings)
    try:
        asyncio.run(system.run())
    except KeyboardInterrupt:
        print("Interrupted, shutting down...")


def _resolve_default_mode() -> str:
    raw = str(os.getenv("HFT_MODE", "sim")).strip().lower()
    if raw == "real":
        return "live"
    if raw not in {"sim", "live", "replay"}:
        return "sim"
    return raw


def cmd_init(args: argparse.Namespace) -> None:
    """Question-lite init that drops a settings.py and a strategy skeleton."""
    strategy_id = args.strategy_id or "my_strategy"
    symbol = args.symbol or "2330"
    settings_tpl = (
        textwrap.dedent(
            f"""
        # Generated by hft init
        def get_settings():
            return {{
                "mode": "sim",
                "symbols": ["{symbol}"],
                "strategy": {{
                    "id": "{strategy_id}",
                    "module": "hft_platform.strategies.{strategy_id}",
                    "class": "Strategy",
                    "params": {{}},
                }},
                "paths": {{
                    "symbols": "config/symbols.yaml",
                    "strategy_limits": "config/base/strategy_limits.yaml",
                    "order_adapter": "config/base/order_adapter.yaml",
                }},
                "prometheus_port": 9090,
            }}
        """
        ).strip()
        + "\n"
    )

    strategy_tpl = (
        textwrap.dedent(
            f"""
        from structlog import get_logger
        from hft_platform.events import LOBStatsEvent
        from hft_platform.strategy.base import BaseStrategy

        logger = get_logger("{strategy_id}")


        class Strategy(BaseStrategy):
            default_params = {{"min_spread": 100, "qty": 1}}

            def __init__(self, strategy_id: str, **params):
                super().__init__(strategy_id)
                self.params = {{**self.default_params, **(params or {{}})}}
                self.symbols = {{"{symbol}"}}

            def on_stats(self, event: LOBStatsEvent):
                if event.symbol not in self.symbols:
                    return
                if event.spread <= self.params["min_spread"]:
                    return
                self.buy(event.symbol, event.best_bid, self.params["qty"])
                logger.info("placing order", price=event.best_bid, params=self.params)
        """
        ).strip()
        + "\n"
    )

    test_tpl = (
        textwrap.dedent(
            f"""
        import pytest
        from hft_platform.core.pricing import PriceCodec, SymbolMetadataPriceScaleProvider
        from hft_platform.strategies.{strategy_id} import Strategy
        from hft_platform.contracts.strategy import OrderIntent
        from hft_platform.events import LOBStatsEvent
        from hft_platform.feed_adapter.normalizer import SymbolMetadata
        from hft_platform.strategy.base import StrategyContext


        def _intent_factory(**kwargs):
            kwargs.setdefault("intent_id", 1)
            kwargs.setdefault("timestamp_ns", 0)
            return OrderIntent(**kwargs)

        def test_strategy_emits_intent():
            strat = Strategy(strategy_id="{strategy_id}")
            metadata = SymbolMetadata()
            price_codec = PriceCodec(SymbolMetadataPriceScaleProvider(metadata))
            ctx = StrategyContext(
                positions={{}},
                strategy_id="{strategy_id}",
                intent_factory=_intent_factory,
                price_scaler=price_codec.scale,
                lob_source=None,
            )
            event = LOBStatsEvent(
                symbol="{symbol}",
                ts=0,
                imbalance=0.0,
                best_bid=1000000,
                best_ask=1000200,
                bid_depth=10,
                ask_depth=10,
            )
            intents = strat.handle_event(ctx, event)
            assert intents, "strategy should emit intent on wide spread"
        """
        ).strip()
        + "\n"
    )

    _safe_write("config/settings.py", settings_tpl)
    _safe_write(f"src/hft_platform/strategies/{strategy_id}.py", strategy_tpl)
    _safe_write(f"tests/test_{strategy_id}.py", test_tpl)

    print("Initialized settings and strategy skeleton.")
    print(f"- config/settings.py\n- src/hft_platform/strategies/{strategy_id}.py\n- tests/test_{strategy_id}.py")
    print("Next steps: `hft run sim --strategy {strategy_id}` or `pytest -k test_{strategy_id}`")


def cmd_check(args: argparse.Namespace) -> None:
    settings, defaults = load_settings()
    missing = []
    if not settings.get("symbols"):
        missing.append("symbols")
    strat = settings.get("strategy", {})
    if not strat.get("id"):
        missing.append("strategy.id")
    if missing:
        print("Config errors:", ", ".join(missing))
        sys.exit(1)

    print("Configuration is valid.")
    if args.export:
        out = "config/exported_settings." + args.export
        if args.export == "yaml":
            try:
                import yaml

                payload = yaml.safe_dump(settings)
            except Exception as exc:
                logger.debug("operation_fallback", error=str(exc))
                payload = json.dumps(settings, indent=2)
        else:
            payload = json.dumps(settings, indent=2)
        _safe_write(out, payload)
        print(f"Exported effective settings to {out}")


def cmd_wizard(args: argparse.Namespace) -> None:
    from hft_platform.config.wizard import run_wizard

    run_wizard()
