"""DoD-B3: predicted q_hat from re-running calibration matches the committed
fixtures within tolerance.

Tolerances
----------
- TMFD6: relative ±15% (mean q_hat ≈ 0.258 — relative metric is stable).
- TXFD6: relative ±15% (mean q_hat ≈ 0.112 — mostly saturated cells).
- TXO35000Q6: absolute ±0.005 (mean q_hat ≈ 0.002 — relative metric blows up
  near zero, so we fall back to absolute tolerance per the plan).

Why this passes deterministically
---------------------------------
Task 6's calibration walk is deterministic: given identical input events it
produces identical attempts/fills tallies. The committed q_hat parquets in
``research/backtest/q_hat_data/`` were generated by Task 7 from the same
per-day raw-replay parquets in ``tests/fixtures/q_hat_calibration/``. Re-running
the calibration on those fixtures here MUST produce values that match the
committed fixtures within numerical-determinism tolerance (effectively zero
diff modulo float ordering, which we cushion with the per-symbol tolerances
above).

If this test goes red, either (a) Task 6's harness gained nondeterminism, or
(b) the committed Task 7 parquets are stale relative to the per-day raw
fixtures.

What this test does NOT validate
--------------------------------
Live↔replay parity (the actual maker-realism shadow comparison) is the job of
Slice C / Slice D. This test is the offline determinism gate: "the calibrated
table that Task 8 wires up matches what re-calibrating right now would yield."
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pyarrow.parquet as pq
import pytest

from research.backtest.calibrate_queue_fill import calibrate
from research.backtest.q_hat_table import QHatTable

_REPO_ROOT = Path(__file__).resolve().parents[2]
_FIXTURE_ROOT = _REPO_ROOT / "tests" / "fixtures" / "q_hat_calibration"
_QHAT_ROOT = _REPO_ROOT / "research" / "backtest" / "q_hat_data"


# Match research/backtest/calibrate_queue_fill.py + ch_data_source._event_dtype
# at the field subset the harness consumes. The committed replay-actual fixtures
# only carry (ev, exch_ts, px, qty); the rest of the dtype fields are zero-filled
# so the structured array shape lines up with what _ingest_day expects.
_EVENT_DTYPE = np.dtype(
    [
        ("ev", "u8"),
        ("exch_ts", "i8"),
        ("local_ts", "i8"),
        ("px", "f8"),
        ("qty", "f8"),
        ("order_id", "u8"),
        ("ival", "i8"),
        ("fval", "f8"),
    ]
)


class _LocalReplaySource:
    """Reads Task 7's per-day raw-replay parquets as a ChDataSourceLike."""

    def __init__(self, fixture_root: Path, symbol: str) -> None:
        self._root = fixture_root
        self._symbol = symbol

    def load_day(self, instrument: str, date: str) -> np.ndarray:
        """Re-hydrate the parquet to the structured array layout the harness wants."""
        path = self._root / f"{instrument}_{date}_replay_actual.parquet"
        if not path.exists():
            return np.array([], dtype=_EVENT_DTYPE)
        arrow_table = pq.read_table(str(path))
        df = arrow_table.to_pandas()
        out = np.zeros(len(df), dtype=_EVENT_DTYPE)
        out["ev"] = df["ev"].to_numpy()
        out["exch_ts"] = df["exch_ts"].to_numpy()
        out["px"] = df["px"].to_numpy()
        out["qty"] = df["qty"].to_numpy()
        # local_ts/order_id/ival/fval not used by the harness — leave as zero.
        return out

    def available_dates(self) -> list[str]:
        return sorted(p.stem.split("_")[1] for p in self._root.glob(f"{self._symbol}_*_replay_actual.parquet"))


@pytest.mark.parametrize(
    "symbol,parquet_name,tolerance,kind",
    [
        ("TMFD6", "tmfd6_q_hat.parquet", 0.15, "relative"),
        ("TXFD6", "txfd6_q_hat.parquet", 0.15, "relative"),
        ("TXO35000Q6", "txo35000q6_q_hat.parquet", 0.005, "absolute"),
    ],
)
def test_predicted_qhat_matches_committed_fixture(
    symbol: str,
    parquet_name: str,
    tolerance: float,
    kind: str,
    tmp_path: Path,
) -> None:
    """Re-run Task 6's calibration on Task 7's raw fixtures and compare cell-by-cell."""
    committed = QHatTable.load(_QHAT_ROOT / parquet_name)
    source = _LocalReplaySource(_FIXTURE_ROOT, symbol)
    dates = source.available_dates()

    assert dates, f"no per-day raw fixtures found for {symbol} under {_FIXTURE_ROOT}"
    assert committed._data, f"committed q_hat parquet for {symbol} is empty — Task 7 may be stale"

    redo_path = tmp_path / parquet_name
    result = calibrate(symbol, dates, redo_path, ch_source=source)

    # Every committed cell must be reproducible from the same fixtures.
    missing_in_redo: list[tuple] = []
    diffs: list[str] = []
    for key, actual in committed._data.items():
        predicted = result.table._data.get(key)
        if predicted is None:
            missing_in_redo.append(key)
            continue
        if kind == "relative":
            denom = max(abs(actual), 1e-6)
            if abs(predicted - actual) / denom >= tolerance:
                diffs.append(
                    f"{symbol} cell {key}: predicted={predicted:.6f} actual={actual:.6f}"
                    f" rel_err={abs(predicted - actual) / denom:.4f}"
                )
        else:  # absolute
            if abs(predicted - actual) >= tolerance:
                diffs.append(
                    f"{symbol} cell {key}: predicted={predicted:.6f} actual={actual:.6f}"
                    f" abs_err={abs(predicted - actual):.6f}"
                )

    assert not missing_in_redo, f"{symbol}: cells in committed parquet missing from re-calibration: {missing_in_redo}"
    assert not diffs, f"{symbol}: per-cell tolerance violations:\n" + "\n".join(diffs)
