# Auto-refreshed by QuoteConnectionPool
# TXO nearest expiry: 2026/04/15
# Group 0: Base (1)
# Group 1: TXO Calls (178)
# Group 2: TXO Puts (178)

symbols:
- code: TXFR1
  exchange: TAIFEX
  group: 0
- code: TXO26500D6
  exchange: OPT
  group: 1
- code: TXO26600D6
  exchange: OPT
  group: 1
- code: TXO26700D6
  exchange: OPT
  group: 1
- code: TXO26800D6
  exchange: OPT
  group: 1
- code: TXO26900D6
  exchange: OPT
  group: 1
- code: TXO27000D6
  exchange: OPT
  group: 1
- code: TXO27100D6
  exchange: OPT
  group: 1
- code: TXO27200D6
  exchange: OPT
  group: 1
- code: TXO27300D6
  exchange: OPT
  group: 1
- code: TXO27400D6
  exchange: OPT
  group: 1
- code: TXO27500D6
  exchange: OPT
  group: 1
- code: TXO27600D6
  exchange: OPT
  group: 1
- code: TXO27700D6
  exchange: OPT
  group: 1
- code: TXO27800D6
  exchange: OPT
  group: 1
- code: TXO27900D6
  exchange: OPT
  group: 1
- code: TXO28000D6
  exchange: OPT
  group: 1
- code: TXO28100D6
  exchange: OPT
  group: 1
- code: TXO28200D6
  exchange: OPT
  group: 1
- code: TXO28300D6
  exchange: OPT
  group: 1
- code: TXO28400D6
  exchange: OPT
  group: 1
- code: TXO28500D6
  exchange: OPT
  group: 1
- code: TXO28600D6
  exchange: OPT
  group: 1
- code: TXO28700D6
  exchange: OPT
  group: 1
- code: TXO28800D6
  exchange: OPT
  group: 1
- code: TXO28900D6
  exchange: OPT
  group: 1
- code: TXO29000D6
  exchange: OPT
  group: 1
- code: TXO29100D6
  exchange: OPT
  group: 1
- code: TXO29200D6
  exchange: OPT
  group: 1
- code: TXO29300D6
  exchange: OPT
  group: 1
- code: TXO29400D6
  exchange: OPT
  group: 1
- code: TXO29500D6
  exchange: OPT
  group: 1
- code: TXO29600D6
  exchange: OPT
  group: 1
- code: TXO29700D6
  exchange: OPT
  group: 1
- code: TXO29800D6
  exchange: OPT
  group: 1
- code: TXO29900D6
  exchange: OPT
  group: 1
- code: TXO30000D6
  exchange: OPT
  group: 1
- code: TXO30100D6
  exchange: OPT
  group: 1
- code: TXO30200D6
  exchange: OPT
  group: 1
- code: TXO30300D6
  exchange: OPT
  group: 1
- code: TXO30400D6
  exchange: OPT
  group: 1
- code: TXO30500D6
  exchange: OPT
  group: 1
- code: TXO30600D6
  exchange: OPT
  group: 1
- code: TXO30700D6
  exchange: OPT
  group: 1
- code: TXO30800D6
  exchange: OPT
  group: 1
- code: TXO30850D6
  exchange: OPT
  group: 1
- code: TXO30900D6
  exchange: OPT
  group: 1
- code: TXO30950D6
  exchange: OPT
  group: 1
- code: TXO31000D6
  exchange: OPT
  group: 1
- code: TXO31050D6
  exchange: OPT
  group: 1
- code: TXO31100D6
  exchange: OPT
  group: 1
- code: TXO31150D6
  exchange: OPT
  group: 1
- code: TXO31200D6
  exchange: OPT
  group: 1
- code: TXO31250D6
  exchange: OPT
  group: 1
- code: TXO31300D6
  exchange: OPT
  group: 1
- code: TXO31350D6
  exchange: OPT
  group: 1
- code: TXO31400D6
  exchange: OPT
  group: 1
- code: TXO31450D6
  exchange: OPT
  group: 1
- code: TXO31500D6
  exchange: OPT
  group: 1
- code: TXO31550D6
  exchange: OPT
  group: 1
- code: TXO31600D6
  exchange: OPT
  group: 1
- code: TXO31650D6
  exchange: OPT
  group: 1
- code: TXO31700D6
  exchange: OPT
  group: 1
- code: TXO31750D6
  exchange: OPT
  group: 1
- code: TXO31800D6
  exchange: OPT
  group: 1
- code: TXO31850D6
  exchange: OPT
  group: 1
- code: TXO31900D6
  exchange: OPT
  group: 1
- code: TXO31950D6
  exchange: OPT
  group: 1
- code: TXO32000D6
  exchange: OPT
  group: 1
- code: TXO32050D6
  exchange: OPT
  group: 1
- code: TXO32100D6
  exchange: OPT
  group: 1
- code: TXO32150D6
  exchange: OPT
  group: 1
- code: TXO32200D6
  exchange: OPT
  group: 1
- code: TXO32250D6
  exchange: OPT
  group: 1
- code: TXO32300D6
  exchange: OPT
  group: 1
- code: TXO32350D6
  exchange: OPT
  group: 1
- code: TXO32400D6
  exchange: OPT
  group: 1
- code: TXO32450D6
  exchange: OPT
  group: 1
- code: TXO32500D6
  exchange: OPT
  group: 1
- code: TXO32550D6
  exchange: OPT
  group: 1
- code: TXO32600D6
  exchange: OPT
  group: 1
- code: TXO32650D6
  exchange: OPT
  group: 1
- code: TXO32700D6
  exchange: OPT
  group: 1
- code: TXO32750D6
  exchange: OPT
  group: 1
- code: TXO32800D6
  exchange: OPT
  group: 1
- code: TXO32850D6
  exchange: OPT
  group: 1
- code: TXO32900D6
  exchange: OPT
  group: 1
- code: TXO32950D6
  exchange: OPT
  group: 1
- code: TXO33000D6
  exchange: OPT
  group: 1
- code: TXO33050D6
  exchange: OPT
  group: 1
- code: TXO33100D6
  exchange: OPT
  group: 1
- code: TXO33150D6
  exchange: OPT
  group: 1
- code: TXO33200D6
  exchange: OPT
  group: 1
- code: TXO33250D6
  exchange: OPT
  group: 1
- code: TXO33300D6
  exchange: OPT
  group: 1
- code: TXO33350D6
  exchange: OPT
  group: 1
- code: TXO33400D6
  exchange: OPT
  group: 1
- code: TXO33450D6
  exchange: OPT
  group: 1
- code: TXO33500D6
  exchange: OPT
  group: 1
- code: TXO33550D6
  exchange: OPT
  group: 1
- code: TXO33600D6
  exchange: OPT
  group: 1
- code: TXO33650D6
  exchange: OPT
  group: 1
- code: TXO33700D6
  exchange: OPT
  group: 1
- code: TXO33750D6
  exchange: OPT
  group: 1
- code: TXO33800D6
  exchange: OPT
  group: 1
- code: TXO33850D6
  exchange: OPT
  group: 1
- code: TXO33900D6
  exchange: OPT
  group: 1
- code: TXO33950D6
  exchange: OPT
  group: 1
- code: TXO34000D6
  exchange: OPT
  group: 1
- code: TXO34050D6
  exchange: OPT
  group: 1
- code: TXO34100D6
  exchange: OPT
  group: 1
- code: TXO34150D6
  exchange: OPT
  group: 1
- code: TXO34200D6
  exchange: OPT
  group: 1
- code: TXO34300D6
  exchange: OPT
  group: 1
- code: TXO34400D6
  exchange: OPT
  group: 1
- code: TXO34500D6
  exchange: OPT
  group: 1
- code: TXO34600D6
  exchange: OPT
  group: 1
- code: TXO34700D6
  exchange: OPT
  group: 1
- code: TXO34800D6
  exchange: OPT
  group: 1
- code: TXO34900D6
  exchange: OPT
  group: 1
- code: TXO35000D6
  exchange: OPT
  group: 1
- code: TXO35100D6
  exchange: OPT
  group: 1
- code: TXO35200D6
  exchange: OPT
  group: 1
- code: TXO35300D6
  exchange: OPT
  group: 1
- code: TXO35400D6
  exchange: OPT
  group: 1
- code: TXO35500D6
  exchange: OPT
  group: 1
- code: TXO35600D6
  exchange: OPT
  group: 1
- code: TXO35700D6
  exchange: OPT
  group: 1
- code: TXO35800D6
  exchange: OPT
  group: 1
- code: TXO35900D6
  exchange: OPT
  group: 1
- code: TXO36000D6
  exchange: OPT
  group: 1
- code: TXO36100D6
  exchange: OPT
  group: 1
- code: TXO36200D6
  exchange: OPT
  group: 1
- code: TXO36300D6
  exchange: OPT
  group: 1
- code: TXO36400D6
  exchange: OPT
  group: 1
- code: TXO36500D6
  exchange: OPT
  group: 1
- code: TXO36600D6
  exchange: OPT
  group: 1
- code: TXO36700D6
  exchange: OPT
  group: 1
- code: TXO36800D6
  exchange: OPT
  group: 1
- code: TXO36900D6
  exchange: OPT
  group: 1
- code: TXO37000D6
  exchange: OPT
  group: 1
- code: TXO37100D6
  exchange: OPT
  group: 1
- code: TXO37200D6
  exchange: OPT
  group: 1
- code: TXO37300D6
  exchange: OPT
  group: 1
- code: TXO37400D6
  exchange: OPT
  group: 1
- code: TXO37500D6
  exchange: OPT
  group: 1
- code: TXO37600D6
  exchange: OPT
  group: 1
- code: TXO37700D6
  exchange: OPT
  group: 1
- code: TXO37800D6
  exchange: OPT
  group: 1
- code: TXO37900D6
  exchange: OPT
  group: 1
- code: TXO38000D6
  exchange: OPT
  group: 1
- code: TXO38100D6
  exchange: OPT
  group: 1
- code: TXO38200D6
  exchange: OPT
  group: 1
- code: TXO38300D6
  exchange: OPT
  group: 1
- code: TXO38400D6
  exchange: OPT
  group: 1
- code: TXO38500D6
  exchange: OPT
  group: 1
- code: TXO38600D6
  exchange: OPT
  group: 1
- code: TXO38700D6
  exchange: OPT
  group: 1
- code: TXO38800D6
  exchange: OPT
  group: 1
- code: TXO38900D6
  exchange: OPT
  group: 1
- code: TXO39000D6
  exchange: OPT
  group: 1
- code: TXO39100D6
  exchange: OPT
  group: 1
- code: TXO39200D6
  exchange: OPT
  group: 1
- code: TXO39300D6
  exchange: OPT
  group: 1
- code: TXO39400D6
  exchange: OPT
  group: 1
- code: TXO39500D6
  exchange: OPT
  group: 1
- code: TXO39600D6
  exchange: OPT
  group: 1
- code: TXO39700D6
  exchange: OPT
  group: 1
- code: TXO39800D6
  exchange: OPT
  group: 1
- code: TXO39900D6
  exchange: OPT
  group: 1
- code: TXO40000D6
  exchange: OPT
  group: 1
- code: TXO40100D6
  exchange: OPT
  group: 1
- code: TXO40200D6
  exchange: OPT
  group: 1
- code: TXO40300D6
  exchange: OPT
  group: 1
- code: TXO40400D6
  exchange: OPT
  group: 1
- code: TXO40500D6
  exchange: OPT
  group: 1
- code: TXO40600D6
  exchange: OPT
  group: 1
- code: TXO40700D6
  exchange: OPT
  group: 1
- code: TXO40800D6
  exchange: OPT
  group: 1
- code: TXO26500P6
  exchange: OPT
  group: 2
- code: TXO26600P6
  exchange: OPT
  group: 2
- code: TXO26700P6
  exchange: OPT
  group: 2
- code: TXO26800P6
  exchange: OPT
  group: 2
- code: TXO26900P6
  exchange: OPT
  group: 2
- code: TXO27000P6
  exchange: OPT
  group: 2
- code: TXO27100P6
  exchange: OPT
  group: 2
- code: TXO27200P6
  exchange: OPT
  group: 2
- code: TXO27300P6
  exchange: OPT
  group: 2
- code: TXO27400P6
  exchange: OPT
  group: 2
- code: TXO27500P6
  exchange: OPT
  group: 2
- code: TXO27600P6
  exchange: OPT
  group: 2
- code: TXO27700P6
  exchange: OPT
  group: 2
- code: TXO27800P6
  exchange: OPT
  group: 2
- code: TXO27900P6
  exchange: OPT
  group: 2
- code: TXO28000P6
  exchange: OPT
  group: 2
- code: TXO28100P6
  exchange: OPT
  group: 2
- code: TXO28200P6
  exchange: OPT
  group: 2
- code: TXO28300P6
  exchange: OPT
  group: 2
- code: TXO28400P6
  exchange: OPT
  group: 2
- code: TXO28500P6
  exchange: OPT
  group: 2
- code: TXO28600P6
  exchange: OPT
  group: 2
- code: TXO28700P6
  exchange: OPT
  group: 2
- code: TXO28800P6
  exchange: OPT
  group: 2
- code: TXO28900P6
  exchange: OPT
  group: 2
- code: TXO29000P6
  exchange: OPT
  group: 2
- code: TXO29100P6
  exchange: OPT
  group: 2
- code: TXO29200P6
  exchange: OPT
  group: 2
- code: TXO29300P6
  exchange: OPT
  group: 2
- code: TXO29400P6
  exchange: OPT
  group: 2
- code: TXO29500P6
  exchange: OPT
  group: 2
- code: TXO29600P6
  exchange: OPT
  group: 2
- code: TXO29700P6
  exchange: OPT
  group: 2
- code: TXO29800P6
  exchange: OPT
  group: 2
- code: TXO29900P6
  exchange: OPT
  group: 2
- code: TXO30000P6
  exchange: OPT
  group: 2
- code: TXO30100P6
  exchange: OPT
  group: 2
- code: TXO30200P6
  exchange: OPT
  group: 2
- code: TXO30300P6
  exchange: OPT
  group: 2
- code: TXO30400P6
  exchange: OPT
  group: 2
- code: TXO30500P6
  exchange: OPT
  group: 2
- code: TXO30600P6
  exchange: OPT
  group: 2
- code: TXO30700P6
  exchange: OPT
  group: 2
- code: TXO30800P6
  exchange: OPT
  group: 2
- code: TXO30850P6
  exchange: OPT
  group: 2
- code: TXO30900P6
  exchange: OPT
  group: 2
- code: TXO30950P6
  exchange: OPT
  group: 2
- code: TXO31000P6
  exchange: OPT
  group: 2
- code: TXO31050P6
  exchange: OPT
  group: 2
- code: TXO31100P6
  exchange: OPT
  group: 2
- code: TXO31150P6
  exchange: OPT
  group: 2
- code: TXO31200P6
  exchange: OPT
  group: 2
- code: TXO31250P6
  exchange: OPT
  group: 2
- code: TXO31300P6
  exchange: OPT
  group: 2
- code: TXO31350P6
  exchange: OPT
  group: 2
- code: TXO31400P6
  exchange: OPT
  group: 2
- code: TXO31450P6
  exchange: OPT
  group: 2
- code: TXO31500P6
  exchange: OPT
  group: 2
- code: TXO31550P6
  exchange: OPT
  group: 2
- code: TXO31600P6
  exchange: OPT
  group: 2
- code: TXO31650P6
  exchange: OPT
  group: 2
- code: TXO31700P6
  exchange: OPT
  group: 2
- code: TXO31750P6
  exchange: OPT
  group: 2
- code: TXO31800P6
  exchange: OPT
  group: 2
- code: TXO31850P6
  exchange: OPT
  group: 2
- code: TXO31900P6
  exchange: OPT
  group: 2
- code: TXO31950P6
  exchange: OPT
  group: 2
- code: TXO32000P6
  exchange: OPT
  group: 2
- code: TXO32050P6
  exchange: OPT
  group: 2
- code: TXO32100P6
  exchange: OPT
  group: 2
- code: TXO32150P6
  exchange: OPT
  group: 2
- code: TXO32200P6
  exchange: OPT
  group: 2
- code: TXO32250P6
  exchange: OPT
  group: 2
- code: TXO32300P6
  exchange: OPT
  group: 2
- code: TXO32350P6
  exchange: OPT
  group: 2
- code: TXO32400P6
  exchange: OPT
  group: 2
- code: TXO32450P6
  exchange: OPT
  group: 2
- code: TXO32500P6
  exchange: OPT
  group: 2
- code: TXO32550P6
  exchange: OPT
  group: 2
- code: TXO32600P6
  exchange: OPT
  group: 2
- code: TXO32650P6
  exchange: OPT
  group: 2
- code: TXO32700P6
  exchange: OPT
  group: 2
- code: TXO32750P6
  exchange: OPT
  group: 2
- code: TXO32800P6
  exchange: OPT
  group: 2
- code: TXO32850P6
  exchange: OPT
  group: 2
- code: TXO32900P6
  exchange: OPT
  group: 2
- code: TXO32950P6
  exchange: OPT
  group: 2
- code: TXO33000P6
  exchange: OPT
  group: 2
- code: TXO33050P6
  exchange: OPT
  group: 2
- code: TXO33100P6
  exchange: OPT
  group: 2
- code: TXO33150P6
  exchange: OPT
  group: 2
- code: TXO33200P6
  exchange: OPT
  group: 2
- code: TXO33250P6
  exchange: OPT
  group: 2
- code: TXO33300P6
  exchange: OPT
  group: 2
- code: TXO33350P6
  exchange: OPT
  group: 2
- code: TXO33400P6
  exchange: OPT
  group: 2
- code: TXO33450P6
  exchange: OPT
  group: 2
- code: TXO33500P6
  exchange: OPT
  group: 2
- code: TXO33550P6
  exchange: OPT
  group: 2
- code: TXO33600P6
  exchange: OPT
  group: 2
- code: TXO33650P6
  exchange: OPT
  group: 2
- code: TXO33700P6
  exchange: OPT
  group: 2
- code: TXO33750P6
  exchange: OPT
  group: 2
- code: TXO33800P6
  exchange: OPT
  group: 2
- code: TXO33850P6
  exchange: OPT
  group: 2
- code: TXO33900P6
  exchange: OPT
  group: 2
- code: TXO33950P6
  exchange: OPT
  group: 2
- code: TXO34000P6
  exchange: OPT
  group: 2
- code: TXO34050P6
  exchange: OPT
  group: 2
- code: TXO34100P6
  exchange: OPT
  group: 2
- code: TXO34150P6
  exchange: OPT
  group: 2
- code: TXO34200P6
  exchange: OPT
  group: 2
- code: TXO34300P6
  exchange: OPT
  group: 2
- code: TXO34400P6
  exchange: OPT
  group: 2
- code: TXO34500P6
  exchange: OPT
  group: 2
- code: TXO34600P6
  exchange: OPT
  group: 2
- code: TXO34700P6
  exchange: OPT
  group: 2
- code: TXO34800P6
  exchange: OPT
  group: 2
- code: TXO34900P6
  exchange: OPT
  group: 2
- code: TXO35000P6
  exchange: OPT
  group: 2
- code: TXO35100P6
  exchange: OPT
  group: 2
- code: TXO35200P6
  exchange: OPT
  group: 2
- code: TXO35300P6
  exchange: OPT
  group: 2
- code: TXO35400P6
  exchange: OPT
  group: 2
- code: TXO35500P6
  exchange: OPT
  group: 2
- code: TXO35600P6
  exchange: OPT
  group: 2
- code: TXO35700P6
  exchange: OPT
  group: 2
- code: TXO35800P6
  exchange: OPT
  group: 2
- code: TXO35900P6
  exchange: OPT
  group: 2
- code: TXO36000P6
  exchange: OPT
  group: 2
- code: TXO36100P6
  exchange: OPT
  group: 2
- code: TXO36200P6
  exchange: OPT
  group: 2
- code: TXO36300P6
  exchange: OPT
  group: 2
- code: TXO36400P6
  exchange: OPT
  group: 2
- code: TXO36500P6
  exchange: OPT
  group: 2
- code: TXO36600P6
  exchange: OPT
  group: 2
- code: TXO36700P6
  exchange: OPT
  group: 2
- code: TXO36800P6
  exchange: OPT
  group: 2
- code: TXO36900P6
  exchange: OPT
  group: 2
- code: TXO37000P6
  exchange: OPT
  group: 2
- code: TXO37100P6
  exchange: OPT
  group: 2
- code: TXO37200P6
  exchange: OPT
  group: 2
- code: TXO37300P6
  exchange: OPT
  group: 2
- code: TXO37400P6
  exchange: OPT
  group: 2
- code: TXO37500P6
  exchange: OPT
  group: 2
- code: TXO37600P6
  exchange: OPT
  group: 2
- code: TXO37700P6
  exchange: OPT
  group: 2
- code: TXO37800P6
  exchange: OPT
  group: 2
- code: TXO37900P6
  exchange: OPT
  group: 2
- code: TXO38000P6
  exchange: OPT
  group: 2
- code: TXO38100P6
  exchange: OPT
  group: 2
- code: TXO38200P6
  exchange: OPT
  group: 2
- code: TXO38300P6
  exchange: OPT
  group: 2
- code: TXO38400P6
  exchange: OPT
  group: 2
- code: TXO38500P6
  exchange: OPT
  group: 2
- code: TXO38600P6
  exchange: OPT
  group: 2
- code: TXO38700P6
  exchange: OPT
  group: 2
- code: TXO38800P6
  exchange: OPT
  group: 2
- code: TXO38900P6
  exchange: OPT
  group: 2
- code: TXO39000P6
  exchange: OPT
  group: 2
- code: TXO39100P6
  exchange: OPT
  group: 2
- code: TXO39200P6
  exchange: OPT
  group: 2
- code: TXO39300P6
  exchange: OPT
  group: 2
- code: TXO39400P6
  exchange: OPT
  group: 2
- code: TXO39500P6
  exchange: OPT
  group: 2
- code: TXO39600P6
  exchange: OPT
  group: 2
- code: TXO39700P6
  exchange: OPT
  group: 2
- code: TXO39800P6
  exchange: OPT
  group: 2
- code: TXO39900P6
  exchange: OPT
  group: 2
- code: TXO40000P6
  exchange: OPT
  group: 2
- code: TXO40100P6
  exchange: OPT
  group: 2
- code: TXO40200P6
  exchange: OPT
  group: 2
- code: TXO40300P6
  exchange: OPT
  group: 2
- code: TXO40400P6
  exchange: OPT
  group: 2
- code: TXO40500P6
  exchange: OPT
  group: 2
- code: TXO40600P6
  exchange: OPT
  group: 2
- code: TXO40700P6
  exchange: OPT
  group: 2
- code: TXO40800P6
  exchange: OPT
  group: 2
