symbols:
- code: '1101'
  exchange: TSE
- code: '1102'
  exchange: TSE
- code: '1216'
  exchange: TSE
- code: '1301'
  exchange: TSE
- code: '1303'
  exchange: TSE
- code: '1326'
  exchange: TSE
- code: '1402'
  exchange: TSE
- code: '2002'
  exchange: TSE
- code: '2201'
  exchange: TSE
- code: '2207'
  exchange: TSE
- code: '2301'
  exchange: TSE
- code: '2303'
  exchange: TSE
- code: '2308'
  exchange: TSE
- code: '2317'
  exchange: TSE
- code: '2327'
  exchange: TSE
- code: '2330'
  exchange: TSE
- code: '2345'
  exchange: TSE
- code: '2354'
  exchange: TSE
- code: '2357'
  exchange: TSE
- code: '2379'
  exchange: TSE
- code: '2382'
  exchange: TSE
- code: '2395'
  exchange: TSE
- code: '2408'
  exchange: TSE
- code: '2409'
  exchange: TSE
- code: '2412'
  exchange: TSE
- code: '2454'
  exchange: TSE
- code: '2474'
  exchange: TSE
- code: '2603'
  exchange: TSE
- code: '2609'
  exchange: TSE
- code: '2615'
  exchange: TSE
- code: '2801'
  exchange: TSE
- code: '2881'
  exchange: TSE
- code: '2882'
  exchange: TSE
- code: '2883'
  exchange: TSE
- code: '2884'
  exchange: TSE
- code: '2885'
  exchange: TSE
- code: '2886'
  exchange: TSE
- code: '2887'
  exchange: TSE
- code: '2890'
  exchange: TSE
- code: '2891'
  exchange: TSE
- code: '2892'
  exchange: TSE
- code: '2912'
  exchange: TSE
- code: '3008'
  exchange: TSE
- code: '3034'
  exchange: TSE
- code: '3045'
  exchange: TSE
- code: '3711'
  exchange: TSE
- code: '4904'
  exchange: TSE
- code: '4938'
  exchange: TSE
- code: '5871'
  exchange: TSE
- code: '5880'
  exchange: TSE
