"""Identify the source tree this process is actually running.

``HFT_GIT_SHA`` is baked into the image by ``Dockerfile:84`` at build time, and
``src/`` is a bind mount. On THESHOW 2026-08-12 the two had been telling
different stories for four weeks: the image was built 2026-07-17 with
``bfa46e1d``, while every ``scp`` deploy since then changed the running code and
left the variable alone. ``hft_build_info{git_sha}`` — the gauge whose stated
purpose is drift detection — was reporting the stale one.

So the process hashes its own source tree at startup and reports that alongside
the image identity, rather than asserting a build argument it cannot see
through.

**The recipe**, chosen so a human can reproduce any part of it by hand:

* per file, the git blob hash — identical to ``git hash-object <file>``, which
  is the idiom deploy law D3 already uses for baselines;
* over the tree, ``sha256`` of ``"<relative/path> <blob_sha>\\n"`` for every
  ``*.py`` under the package root, sorted by path, truncated to 12 hex chars.

``__pycache__`` and non-Python files are excluded: bytecode is regenerated by
the interpreter and config/output files are written at runtime, so including
either would make the identity change while the code did not.
"""

from __future__ import annotations

import hashlib
import os
from functools import lru_cache
from pathlib import Path
from typing import NamedTuple

from structlog import get_logger

logger = get_logger("observability.code_identity")

# ``.../src/hft_platform`` — the tree that is bind-mounted in production.
_SOURCE_ROOT = Path(__file__).resolve().parent.parent
_SHA_LEN = 12
_UNKNOWN = "unknown"


class CodeIdentity(NamedTuple):
    """What is running, as opposed to what was built."""

    sha: str
    file_count: int
    source_root: str


def _blob_sha1(data: bytes) -> str:
    """git's own object id for ``data`` — matches ``git hash-object``.

    sha1 here is a compatibility requirement, not a security choice: the value
    is only useful because an operator can reproduce it with git.
    """
    digest = hashlib.sha1(b"blob %d\0" % len(data), usedforsecurity=False)  # noqa: S324 - must match git's object id
    digest.update(data)
    return digest.hexdigest()


def compute_code_identity(root: Path | str | None = None) -> CodeIdentity:
    """Hash every ``*.py`` under ``root`` (default: the installed package).

    Never raises. This runs during boot, and a deployment-audit convenience may
    not be the thing that stops the engine from starting.
    """
    src = Path(root) if root is not None else _SOURCE_ROOT
    try:
        paths = sorted(p for p in src.rglob("*.py") if "__pycache__" not in p.parts)
        if not paths:
            return CodeIdentity(_UNKNOWN, 0, str(src))
        digest = hashlib.sha256()
        for path in paths:
            rel = path.relative_to(src).as_posix()
            try:
                blob = _blob_sha1(path.read_bytes())
            except OSError:
                # Not skipped: a file we cannot read must not hash the same as
                # a tree that never had it.
                blob = "UNREADABLE"
            digest.update(f"{rel} {blob}\n".encode())
        return CodeIdentity(digest.hexdigest()[:_SHA_LEN], len(paths), str(src))
    except Exception:  # noqa: BLE001 - boot-path helper, degrade to "unknown"
        logger.warning("code_identity_failed", source_root=str(src), exc_info=True)
        return CodeIdentity(_UNKNOWN, 0, str(src))


@lru_cache(maxsize=1)
def code_identity() -> CodeIdentity:
    """The running tree's identity, computed once per process.

    Walking the source tree costs tens of milliseconds; boot pays for it once
    and every later caller reads the cached value.
    """
    return compute_code_identity()


def running_code_sha() -> str:
    return code_identity().sha


def log_code_identity() -> CodeIdentity:
    """Emit both identities at startup and return the running one.

    Logs are the surface the deploy runbook reads, so the image sha and the code
    sha appear on the same line: seeing them side by side is what stops the next
    reader from trusting the wrong one.
    """
    identity = code_identity()
    logger.info(
        "running_code_identity",
        code_sha=identity.sha,
        files=identity.file_count,
        source_root=identity.source_root,
        image_git_sha=os.environ.get("HFT_GIT_SHA", _UNKNOWN) or _UNKNOWN,
        image_build_ts=os.environ.get("HFT_BUILD_TS", _UNKNOWN) or _UNKNOWN,
    )
    return identity
