#!/usr/bin/env python3
"""Refresh data/live_with_options.yaml with nearest-expiry TXO options.

Usage:
    python scripts/refresh_options_symbols.py [--dry-run]

Requires: SHIOAJI_API_KEY, SHIOAJI_SECRET_KEY env vars.
Reads:    data/live_futures_only.yaml (base stocks + futures)
Writes:   data/live_with_options.yaml (with connection pool groups)

Groups:
    0: Stocks + Futures (from base file)
    1: TXO Calls (nearest expiry, all strikes)
    2: TXO Puts  (nearest expiry, all strikes)
"""
from __future__ import annotations

import os
import sys

import yaml


def main() -> None:
    dry_run = "--dry-run" in sys.argv

    import shioaji as sj

    api = sj.Shioaji()
    api.login(
        os.environ["SHIOAJI_API_KEY"],
        os.environ["SHIOAJI_SECRET_KEY"],
        fetch_contract=True,
    )

    try:
        opts = list(api.Contracts.Options.TXO)
        dates = sorted(set(c.delivery_date for c in opts))
        nearest_date = dates[0]
        nearest = [c for c in opts if c.delivery_date == nearest_date]

        calls = sorted(
            [c for c in nearest if c.option_right.value == "C"],
            key=lambda c: c.strike_price,
        )
        puts = sorted(
            [c for c in nearest if c.option_right.value == "P"],
            key=lambda c: c.strike_price,
        )

        base_path = os.environ.get("BASE_SYMBOLS", "data/live_futures_only.yaml")
        with open(base_path) as f:
            existing = yaml.safe_load(f) or {}
        existing_symbols = existing.get("symbols", [])

        symbols: list[dict] = []
        for sym in existing_symbols:
            entry = dict(sym)
            entry["group"] = 0
            symbols.append(entry)

        futures_codes = {"TXFD6", "TMFD6"}
        existing_codes = {s["code"] for s in existing_symbols}
        for fc in sorted(futures_codes - existing_codes):
            symbols.append({"code": fc, "exchange": "FUT", "group": 0})

        for c in calls:
            symbols.append({"code": c.code, "exchange": "OPT", "group": 1})
        for c in puts:
            symbols.append({"code": c.code, "exchange": "OPT", "group": 2})

        g0 = len([s for s in symbols if s["group"] == 0])
        print(f"Expiry: {nearest_date}")
        print(f"  Group 0: {g0} (stocks+futures)")
        print(f"  Group 1: {len(calls)} (TXO calls)")
        print(f"  Group 2: {len(puts)} (TXO puts)")
        print(f"  Total: {len(symbols)} symbols")

        if dry_run:
            print("[DRY RUN] Would write data/live_with_options.yaml")
            return

        out_path = "data/live_with_options.yaml"
        with open(out_path, "w") as f:
            f.write(f"# Auto-generated by scripts/refresh_options_symbols.py\n")
            f.write(f"# TXO nearest expiry: {nearest_date}\n")
            f.write(f"# Group 0: Stocks + Futures ({g0})\n")
            f.write(f"# Group 1: TXO Calls ({len(calls)})\n")
            f.write(f"# Group 2: TXO Puts ({len(puts)})\n\n")
            yaml.dump({"symbols": symbols}, f, default_flow_style=False, allow_unicode=True)

        print(f"Written: {out_path}")

    finally:
        api.logout()


if __name__ == "__main__":
    main()
