"""``HFT_GIT_SHA`` does not describe the code the engine is running.

Measured on THESHOW 2026-08-12: ``HFT_GIT_SHA=bfa46e1d``, baked into the image
by ``Dockerfile:84`` at build time — and that image was built 2026-07-17.
``src/`` is a bind mount, so every ``scp`` deploy since then changed the running
code without changing the variable. ``hft_build_info{git_sha}``, the gauge whose
whole purpose is drift detection (``metrics.py:1615-1627``), has been reporting
a four-week-old identity as if it were current.

The deploy runbook already works around this by hand: D3 takes a baseline with
``git hash-object`` on the individual file being replaced. This module makes the
process report the same kind of evidence for its whole source tree, so the
answer to "what is actually running?" comes from the process rather than from a
build argument it cannot see through.

The digest is deliberately built out of git blob hashes: any single file's
contribution is reproducible on a dev box with ``git hash-object <file>``, which
is the idiom the runbook already uses.
"""

from __future__ import annotations

import hashlib
import shutil
import subprocess
from pathlib import Path

import pytest

from hft_platform.observability.code_identity import (
    _blob_sha1,
    code_identity,
    compute_code_identity,
    log_code_identity,
    running_code_sha,
)


def _tree(root: Path, files: dict[str, str]) -> Path:
    for rel, body in files.items():
        path = root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(body, encoding="utf-8")
    return root


_SRC = {
    "hft_platform/__init__.py": "__version__ = '1.0'\n",
    "hft_platform/order/adapter.py": "def dispatch():\n    return 1\n",
    "hft_platform/strategies/r47_maker.py": "SPREAD = 5\n",
}


# --------------------------------------------------------------------------- #
# The property that matters: a bind-mounted edit must move the sha             #
# --------------------------------------------------------------------------- #


@pytest.mark.unit
def test_editing_a_source_file_changes_the_code_sha(tmp_path: Path) -> None:
    """The exact scenario the image sha cannot see: one ``scp``'d file."""
    root = _tree(tmp_path, _SRC)
    before = compute_code_identity(root).sha

    (root / "hft_platform/strategies/r47_maker.py").write_text("SPREAD = 3\n", encoding="utf-8")

    assert compute_code_identity(root).sha != before


@pytest.mark.unit
def test_an_unchanged_tree_hashes_the_same_every_time(tmp_path: Path) -> None:
    """A drift signal that drifts on its own is worse than none."""
    root = _tree(tmp_path, _SRC)

    assert compute_code_identity(root).sha == compute_code_identity(root).sha


@pytest.mark.unit
def test_renaming_a_file_changes_the_code_sha(tmp_path: Path) -> None:
    """Content alone is not identity — the path is hashed too, so a moved
    module is a different tree even when every byte is the same."""
    root = _tree(tmp_path, _SRC)
    before = compute_code_identity(root).sha

    (root / "hft_platform/order/adapter.py").rename(root / "hft_platform/order/adapter2.py")

    assert compute_code_identity(root).sha != before


@pytest.mark.unit
def test_adding_a_file_changes_the_code_sha_and_the_count(tmp_path: Path) -> None:
    root = _tree(tmp_path, _SRC)
    before = compute_code_identity(root)

    (root / "hft_platform/order/hotfix.py").write_text("PATCHED = True\n", encoding="utf-8")
    after = compute_code_identity(root)

    assert after.sha != before.sha
    assert after.file_count == before.file_count + 1


@pytest.mark.unit
def test_bytecode_and_data_files_are_not_part_of_the_identity(tmp_path: Path) -> None:
    """``__pycache__`` is regenerated by the interpreter and ``outputs/`` is
    written at runtime; either one in the digest would make the sha change
    without the code changing."""
    root = _tree(tmp_path, _SRC)
    before = compute_code_identity(root)

    (root / "hft_platform/__pycache__").mkdir(parents=True, exist_ok=True)
    (root / "hft_platform/__pycache__/adapter.cpython-312.pyc").write_bytes(b"\x00\x01stale")
    (root / "hft_platform/symbols.yaml").write_text("symbols: []\n", encoding="utf-8")

    after = compute_code_identity(root)
    assert after.sha == before.sha
    assert after.file_count == before.file_count


# --------------------------------------------------------------------------- #
# Reproducible by hand — the point of using git's own object hash              #
# --------------------------------------------------------------------------- #


@pytest.mark.unit
@pytest.mark.skipif(shutil.which("git") is None, reason="needs git to cross-check the blob hash")
def test_a_files_component_is_exactly_what_git_hash_object_prints(tmp_path: Path) -> None:
    """D3 baselines are taken with ``git hash-object``. An operator must be able
    to check one file against this digest's input without running the platform."""
    path = tmp_path / "sample.py"
    path.write_text("def dispatch():\n    return 1\n", encoding="utf-8")

    proc = subprocess.run(["git", "hash-object", str(path)], capture_output=True, text=True, check=True)

    assert _blob_sha1(path.read_bytes()) == proc.stdout.strip()


@pytest.mark.unit
def test_the_digest_is_sha256_over_sorted_path_and_blob_lines(tmp_path: Path) -> None:
    """Pins the documented recipe so the docstring stays a true statement of how
    to reproduce the value off-box."""
    root = _tree(tmp_path, _SRC)

    expected = hashlib.sha256()
    for rel in sorted(_SRC):
        blob = _blob_sha1((root / rel).read_bytes())
        expected.update(f"{rel} {blob}\n".encode())

    assert compute_code_identity(root).sha == expected.hexdigest()[:12]


# --------------------------------------------------------------------------- #
# It runs during boot, so it may never raise                                   #
# --------------------------------------------------------------------------- #


@pytest.mark.unit
def test_a_missing_source_root_reports_unknown_instead_of_raising(tmp_path: Path) -> None:
    identity = compute_code_identity(tmp_path / "not-deployed")

    assert identity.sha == "unknown"
    assert identity.file_count == 0


def _readable(path: Path) -> bool:
    try:
        path.read_bytes()
    except OSError:
        return False
    return True


@pytest.mark.unit
def test_an_unreadable_file_moves_the_sha_rather_than_vanishing(tmp_path: Path) -> None:
    """Skipping a file that cannot be read would report the same identity as a
    tree that never had it — the failure would hide inside the answer."""
    root = _tree(tmp_path, _SRC)
    before = compute_code_identity(root).sha
    victim = root / "hft_platform/order/adapter.py"
    victim.chmod(0o000)
    if _readable(victim):
        victim.chmod(0o644)
        pytest.skip("running as root; chmod does not deny reads")

    after = compute_code_identity(root)
    victim.chmod(0o644)

    assert after.sha != before
    assert after.file_count == 3, "the file is still counted, just not trusted"


# --------------------------------------------------------------------------- #
# What the process actually reports                                            #
# --------------------------------------------------------------------------- #


@pytest.mark.unit
def test_the_real_package_produces_a_real_identity() -> None:
    """Guards against the helper silently degrading to "unknown" in the
    installed layout, which would make every assertion above vacuous in prod."""
    identity = code_identity()

    assert identity.sha != "unknown"
    assert len(identity.sha) == 12
    assert identity.file_count > 100, identity
    assert identity.source_root.endswith("hft_platform")


@pytest.mark.unit
def test_the_build_info_gauge_exposes_the_running_code_sha() -> None:
    """``hft_build_info`` is the drift-detection gauge. Until now every label on
    it described the image."""
    from prometheus_client import REGISTRY

    from hft_platform.observability.metrics import MetricsRegistry, _pn

    MetricsRegistry()

    for metric in REGISTRY.collect():
        if metric.name == _pn("build_info"):
            labels = metric.samples[0].labels
            assert labels.get("code_sha") == running_code_sha()
            assert "git_sha" in labels and "build_ts" in labels
            return
    pytest.fail("build_info gauge not found in the Prometheus registry")


@pytest.mark.unit
def test_the_startup_line_names_the_image_and_the_code_separately(monkeypatch, module_log_sink) -> None:
    """Logs are the surface the deploy runbook actually reads. Both identities
    have to be on the line, or the next reader repeats the same mistake."""
    from hft_platform.observability import code_identity as code_identity_module

    events = module_log_sink(code_identity_module)
    monkeypatch.setenv("HFT_GIT_SHA", "bfa46e1d")
    identity = log_code_identity()

    line = next(entry for entry in events if entry.get("event") == "running_code_identity")
    assert line["code_sha"] == identity.sha
    assert line["image_git_sha"] == "bfa46e1d"
    assert line["files"] == identity.file_count


@pytest.mark.unit
def test_the_identity_is_computed_once_per_process() -> None:
    """It walks every source file; boot must pay for that once, not per caller."""
    first = code_identity()

    assert code_identity() is first
